//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MeshExport.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_COMMENT                     6
#define IDS_GIZMOS                      7
#define IDS_MTL1                        7
#define IDS_GIZMOPARAM_NAME             7
#define IDS_SPIN_OBJ                    7
#define IDS_COORDS                      7
#define IDS_PARAM1                      7
#define IDS_QUALITY                     7
#define IDS_MN_DIFFUSE                  7
#define IDS_MTL1ON                      8
#define IDS_PW_GIZMOCATEGORY            8
#define IDS_PARAM2                      8
#define IDS_ENABLE                      8
#define IDS_MN_BRIGHTNESS               8
#define IDS_AD_ENABLE                   9
#define IDS_MN_OPACITY                  9
#define IDS_AD_THRESH                   10
#define IDS_MN_NONE                     10
#define IDS_COLOR                       11
#define IDS_PARAMCHG                    12
#define IDS_MN_DIFFUSE_I                13
#define IDS_MN_BRIGHTNESS_I             14
#define IDS_MN_OPACITY_I                15
#define IDD_PANEL                       101
#define IDD_ABOUT                       102
#define IDD_PANEL_OBJ                   102
#define IDD_DIALOG1                     103
#define IDD_DIALOG2                     104
#define IDD_EX_MATERIAL_PANEL           105
#define IDD_BITMAP_RELOCATOR            108
#define IDD_BITMAP_RELOCATOR_PANEL      108
#define IDD_DIALOG3                     110
#define IDD_SHADER_SKEL1                148
#define IDC_TR_EDIT                     220
#define IDC_TR_SPIN                     330
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_RADIO1                      1001
#define IDC_RADIO2                      1002
#define IDC_RADIO3                      1003
#define IDC_OK                          1004
#define IDC_BUTTON2                     1005
#define IDC_CANCEL                      1005
#define IDC_LIST1                       1006
#define IDC_RADIO4                      1006
#define IDC_BUTTON6                     1006
#define IDC_CHECK1                      1007
#define IDC_BUTTON7                     1007
#define IDC_EDIT1                       1008
#define IDC_EDIT2                       1009
#define IDC_EDIT3                       1010
#define IDC_CHECK2                      1011
#define IDC_EDIT12                      1011
#define IDC_CHECK3                      1012
#define IDC_EDIT13                      1012
#define IDC_BUTTON1                     1013
#define IDC_EDIT14                      1013
#define IDC_BUTTON3                     1014
#define IDC_CHECK4                      1015
#define IDC_BUTTON8                     1015
#define IDC_EDIT4                       1016
#define IDC_BUTTON9                     1016
#define IDC_EDIT5                       1017
#define IDC_EDIT6                       1018
#define IDC_EDIT7                       1019
#define IDC_EDIT8                       1020
#define IDC_CHECK5                      1021
#define IDC_BUTTON4                     1022
#define IDC_CHECK6                      1023
#define IDC_CHECK7                      1024
#define IDC_EDIT9                       1025
#define IDC_CHECK8                      1026
#define IDC_EDIT10                      1027
#define IDC_CHECK9                      1028
#define IDC_LBL_MATERIAL_NAME           1028
#define IDC_CHECK10                     1029
#define IDC_BTN_GET_ACTIVE_MATERIAL     1029
#define IDC_EDIT11                      1030
#define IDC_BTN_GET_ACTIVE_MATERIAL2    1030
#define IDC_BTN_GET_SELECTED_NODE       1030
#define IDC_CHECK11                     1031
#define IDC_GROUP_PROPERTIES            1031
#define IDC_COMBO_BLEND_OVERRIDE        1032
#define IDC_COMBO_ALPHA_TEST_OVERRIDE   1033
#define IDC_SLOT_ALPHA_TEST_REF         1034
#define IDC_SLOTSPIN_ALPHA_TEST_REF     1035
#define IDC_SLOT_LAYER_INDEX            1036
#define IDC_SLOTSPIN_LAYER_INDEX        1037
#define IDC_MAPON_TR                    1038
#define IDC_LBL_BLEND_OVERRIDE          1038
#define IDC_LBL_ALPHA_TEST_OVERRIDE     1039
#define IDC_LBL_ALPHA_TEST_REF          1040
#define IDC_LBL_LAYER_INDEX             1041
#define IDC_BTN_RESET_MATERIAL_PROPERTIES 1042
#define IDC_LBL_BLEND_MODE_OVERRIDE     1043
#define IDC_COMBO_BLEND_MODE_OVERRIDE   1044
#define IDC_COMBO_DIFFUSE_FILTER_OVERRIDE 1045
#define IDC_LBL_DIFFUSE_FILTER_OVERRIDE 1046
#define IDC_GROUP_EXPLICIT_BLEND_MODE   1047
#define IDC_LBL_SRC_BLEND_FACTOR        1048
#define IDC_COMBO_SRC_BLEND_FACTOR      1049
#define IDC_LBL_DST_BLEND_FACTXOR       1050
#define IDC_LBL_DST_BLEND_FACTOR        1050
#define IDC_COMBO_DST_BLEND_FACTOR      1051
#define IDC_COMBO_BLEND_OP              1052
#define IDC_LBL_BLEND_OP                1053
#define IDC_BTN_RELOCATE_BITMAPS        1054
#define IDC_BTN_MAKE_SPRITE_UV_ANIM     1054
#define IDC_CHECK12                     1057
#define IDC_CHECK13                     1058
#define IDC_CHECK14                     1059
#define IDC_BUTTON5                     1060
#define IDC_LBL_PADDING                 1061
#define IDC_HIGHLIGHT                   1062
#define IDC_GROUP_FRAME_WHOLE           1062
#define IDC_SEP_OPACITY_MAPPING         1063
#define IDC_CHECK_SEP_OPACITY_MAPPING   1063
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_SPIN                        1496
#define IDC_GIZMOLIST                   1497
#define IDC_MTL1                        1497
#define IDC_SPIN_OBJ                    1497
#define IDC_ADDGIZMO                    1498
#define IDC_MTLON1                      1498
#define IDC_NAME                        1498
#define IDC_EDIT_OBJ                    1498
#define IDC_DELGIZMO                    1499
#define IDC_BR_EDIT                     1807
#define IDC_BR_SPIN                     1808
#define IDC_MAPON_BR                    1809
#define IDC_MAPON_CLR                   1814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
