/** \file
 *  This C header file was generated by $ANTLR version 3.1.3 Mar 17, 2009 19:23:44
 *
 *     -  From the grammar source file : grunt.g
 *     -                            On : 2009-03-20 09:47:19
 *     -                for the parser : gruntParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser gruntParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pgruntParser, which is returned from a call to gruntParserNew().
 *
 * The methods in pgruntParser are  as follows:
 *
 *  - gruntParser_prog_return      pgruntParser->prog(pgruntParser)
 *  - gruntParser_stat_return      pgruntParser->stat(pgruntParser)
 *  - gruntParser_local_declaration_stat_return      pgruntParser->local_declaration_stat(pgruntParser)
 *  - gruntParser_function_definition_return      pgruntParser->function_definition(pgruntParser)
 *  - gruntParser_selection_stat_return      pgruntParser->selection_stat(pgruntParser)
 *  - gruntParser_if_stat_return      pgruntParser->if_stat(pgruntParser)
 *  - gruntParser_switch_stat_return      pgruntParser->switch_stat(pgruntParser)
 *  - gruntParser_switch_case_label_return      pgruntParser->switch_case_label(pgruntParser)
 *  - gruntParser_iteration_stat_return      pgruntParser->iteration_stat(pgruntParser)
 *  - gruntParser_for_stat_return      pgruntParser->for_stat(pgruntParser)
 *  - gruntParser_for_init_expr_return      pgruntParser->for_init_expr(pgruntParser)
 *  - gruntParser_for_cond_expr_return      pgruntParser->for_cond_expr(pgruntParser)
 *  - gruntParser_for_loop_expr_return      pgruntParser->for_loop_expr(pgruntParser)
 *  - gruntParser_while_stat_return      pgruntParser->while_stat(pgruntParser)
 *  - gruntParser_do_while_stat_return      pgruntParser->do_while_stat(pgruntParser)
 *  - gruntParser_compound_stat_return      pgruntParser->compound_stat(pgruntParser)
 *  - gruntParser_comma_stat_return      pgruntParser->comma_stat(pgruntParser)
 *  - gruntParser_parameter_list_return      pgruntParser->parameter_list(pgruntParser)
 *  - gruntParser_argument_list_return      pgruntParser->argument_list(pgruntParser)
 *  - gruntParser_expr_return      pgruntParser->expr(pgruntParser)
 *  - gruntParser_assignment_expr_return      pgruntParser->assignment_expr(pgruntParser)
 *  - gruntParser_conditional_expr_return      pgruntParser->conditional_expr(pgruntParser)
 *  - gruntParser_logical_or_expr_return      pgruntParser->logical_or_expr(pgruntParser)
 *  - gruntParser_logical_and_expr_return      pgruntParser->logical_and_expr(pgruntParser)
 *  - gruntParser_bitwise_or_expr_return      pgruntParser->bitwise_or_expr(pgruntParser)
 *  - gruntParser_bitwise_xor_expr_return      pgruntParser->bitwise_xor_expr(pgruntParser)
 *  - gruntParser_bitwise_and_expr_return      pgruntParser->bitwise_and_expr(pgruntParser)
 *  - gruntParser_equality_expr_return      pgruntParser->equality_expr(pgruntParser)
 *  - gruntParser_inequality_expr_return      pgruntParser->inequality_expr(pgruntParser)
 *  - gruntParser_bitwise_shift_expr_return      pgruntParser->bitwise_shift_expr(pgruntParser)
 *  - gruntParser_add_expr_return      pgruntParser->add_expr(pgruntParser)
 *  - gruntParser_mul_expr_return      pgruntParser->mul_expr(pgruntParser)
 *  - gruntParser_pre_unary_expr_return      pgruntParser->pre_unary_expr(pgruntParser)
 *  - gruntParser_post_unary_expr_return      pgruntParser->post_unary_expr(pgruntParser)
 *  - gruntParser_primary_expr_return      pgruntParser->primary_expr(pgruntParser)
 *  - gruntParser_dictionary_value_return      pgruntParser->dictionary_value(pgruntParser)
 *  - gruntParser_string_literal_rule_return      pgruntParser->string_literal_rule(pgruntParser)
 *  - gruntParser_integer_literal_rule_return      pgruntParser->integer_literal_rule(pgruntParser)
 *  - gruntParser_float_literal_rule_return      pgruntParser->float_literal_rule(pgruntParser)
 * 
 * 
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_gruntParser_H
#define _gruntParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct gruntParser_Ctx_struct gruntParser, * pgruntParser;




extern "C++"
{

#include "../z3D/Core/Header.h"
using namespace z3D::Core;
#include "../z3D/Core/z_off_debug_new.h"

	wcs		grunt_unescape_string(const wcs& s);
}



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */
typedef struct gruntParser_prog_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_prog_return;

typedef struct gruntParser_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_stat_return;

typedef struct gruntParser_local_declaration_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_local_declaration_stat_return;

typedef struct gruntParser_function_definition_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_function_definition_return;

typedef struct gruntParser_selection_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_selection_stat_return;

typedef struct gruntParser_if_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_if_stat_return;

typedef struct gruntParser_switch_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_switch_stat_return;

typedef struct gruntParser_switch_case_label_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_switch_case_label_return;

typedef struct gruntParser_iteration_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_iteration_stat_return;

typedef struct gruntParser_for_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_for_stat_return;

typedef struct gruntParser_for_init_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_for_init_expr_return;

typedef struct gruntParser_for_cond_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_for_cond_expr_return;

typedef struct gruntParser_for_loop_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_for_loop_expr_return;

typedef struct gruntParser_while_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_while_stat_return;

typedef struct gruntParser_do_while_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_do_while_stat_return;

typedef struct gruntParser_compound_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_compound_stat_return;

typedef struct gruntParser_comma_stat_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_comma_stat_return;

typedef struct gruntParser_parameter_list_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_parameter_list_return;

typedef struct gruntParser_argument_list_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_argument_list_return;

typedef struct gruntParser_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_expr_return;

typedef struct gruntParser_assignment_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_assignment_expr_return;

typedef struct gruntParser_conditional_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_conditional_expr_return;

typedef struct gruntParser_logical_or_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_logical_or_expr_return;

typedef struct gruntParser_logical_and_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_logical_and_expr_return;

typedef struct gruntParser_bitwise_or_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_bitwise_or_expr_return;

typedef struct gruntParser_bitwise_xor_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_bitwise_xor_expr_return;

typedef struct gruntParser_bitwise_and_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_bitwise_and_expr_return;

typedef struct gruntParser_equality_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_equality_expr_return;

typedef struct gruntParser_inequality_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_inequality_expr_return;

typedef struct gruntParser_bitwise_shift_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_bitwise_shift_expr_return;

typedef struct gruntParser_add_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_add_expr_return;

typedef struct gruntParser_mul_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_mul_expr_return;

typedef struct gruntParser_pre_unary_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_pre_unary_expr_return;

typedef struct gruntParser_post_unary_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_post_unary_expr_return;

typedef struct gruntParser_primary_expr_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_primary_expr_return;

typedef struct gruntParser_dictionary_value_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_dictionary_value_return;

typedef struct gruntParser_string_literal_rule_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_string_literal_rule_return;

typedef struct gruntParser_integer_literal_rule_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_integer_literal_rule_return;

typedef struct gruntParser_float_literal_rule_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    pANTLR3_BASE_TREE	tree;
   
}
    gruntParser_float_literal_rule_return;



/** Context tracking structure for gruntParser
 */
struct gruntParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;


     gruntParser_prog_return (*prog)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_stat_return (*stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_local_declaration_stat_return (*local_declaration_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_function_definition_return (*function_definition)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_selection_stat_return (*selection_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_if_stat_return (*if_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_switch_stat_return (*switch_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_switch_case_label_return (*switch_case_label)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_iteration_stat_return (*iteration_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_for_stat_return (*for_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_for_init_expr_return (*for_init_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_for_cond_expr_return (*for_cond_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_for_loop_expr_return (*for_loop_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_while_stat_return (*while_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_do_while_stat_return (*do_while_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_compound_stat_return (*compound_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_comma_stat_return (*comma_stat)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_parameter_list_return (*parameter_list)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_argument_list_return (*argument_list)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_expr_return (*expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_assignment_expr_return (*assignment_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_conditional_expr_return (*conditional_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_logical_or_expr_return (*logical_or_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_logical_and_expr_return (*logical_and_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_bitwise_or_expr_return (*bitwise_or_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_bitwise_xor_expr_return (*bitwise_xor_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_bitwise_and_expr_return (*bitwise_and_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_equality_expr_return (*equality_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_inequality_expr_return (*inequality_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_bitwise_shift_expr_return (*bitwise_shift_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_add_expr_return (*add_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_mul_expr_return (*mul_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_pre_unary_expr_return (*pre_unary_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_post_unary_expr_return (*post_unary_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_primary_expr_return (*primary_expr)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_dictionary_value_return (*dictionary_value)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_string_literal_rule_return (*string_literal_rule)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_integer_literal_rule_return (*integer_literal_rule)	(struct gruntParser_Ctx_struct * ctx);
     gruntParser_float_literal_rule_return (*float_literal_rule)	(struct gruntParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred1_grunt)	(struct gruntParser_Ctx_struct * ctx);
     ANTLR3_BOOLEAN (*synpred2_grunt)	(struct gruntParser_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct gruntParser_Ctx_struct * ctx);
    /* @headerFile.members() */
    pANTLR3_BASE_TREE_ADAPTOR	adaptor;
    pANTLR3_VECTOR_FACTORY		vectors;
    /* End @headerFile.members() */
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pgruntParser gruntParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
ANTLR3_API pgruntParser gruntParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define OP_BITWISE_AND      21
#define HEXADECIMAL_INTEGER_LITERAL      69
#define OP_LOGICAL_AND      18
#define OP_MUL_ASSIGN      8
#define SWITCH_CASE_LABEL      51
#define CP_BLOCK      46
#define EOF      -1
#define T__93      93
#define T__94      94
#define OP_MOD      32
#define T__91      91
#define T__92      92
#define STRING_LITERAL      65
#define T__90      90
#define OP_NOT_EQUAL      22
#define IF_STAT      49
#define OP_PRE_DECR      41
#define PARAMETER_LIST      48
#define T__99      99
#define T__98      98
#define OP_LOGICAL_OR      17
#define T__97      97
#define T__96      96
#define T__95      95
#define OP_GREATER_EQUAL      27
#define OP_LOGICAL_NOT      38
#define T__80      80
#define OP_GREATER      26
#define T__81      81
#define T__82      82
#define T__83      83
#define THIS_FUNC      61
#define OP_OR_ASSIGN      14
#define OP_ADD      30
#define FOR_STAT      52
#define SWITCH_STAT      50
#define OP_UNARY_MINUS      4
#define OP_MOD_ASSIGN      10
#define OP_DIV      34
#define FUNC_DEF      59
#define STRING_ESC_SEQ      67
#define T__85      85
#define T__84      84
#define T__87      87
#define OP_SUB_ASSIGN      7
#define T__86      86
#define T__89      89
#define T__88      88
#define T__126      126
#define WHILE_STAT      53
#define T__125      125
#define OP_POST_INCR      35
#define T__128      128
#define T__127      127
#define WS      74
#define T__129      129
#define COMMA_BLOCK      45
#define OP_XOR_ASSIGN      15
#define LINE_COMMAND      76
#define SL_COMMENT      72
#define OP_EQUAL      23
#define STRING_BASIC_CHAR      66
#define DECIMAL_INTEGER_LITERAL      68
#define OP_SHIFT_RIGHT_ASSIGN      12
#define T__130      130
#define T__131      131
#define T__132      132
#define T__79      79
#define T__133      133
#define T__78      78
#define T__134      134
#define OP_BITWISE_NOT      37
#define T__77      77
#define OP_CALL_FUNC      44
#define OP_ASSIGN      5
#define OP_CONDITIONAL      16
#define OP_BITWISE_OR      19
#define T__118      118
#define T__119      119
#define T__116      116
#define T__117      117
#define T__114      114
#define T__115      115
#define T__124      124
#define OP_MUL      33
#define T__123      123
#define OP_PRE_INCR      40
#define T__122      122
#define T__121      121
#define T__120      120
#define OP_BITWISE_XOR      20
#define LOCAL_DECLARATION_STAT      55
#define OP_LESS      24
#define ML_COMMENT      73
#define OP_SUB      31
#define OP_INDEX      43
#define OP_LESS_EQUAL      25
#define T__107      107
#define OP_ELEMENT      42
#define T__108      108
#define OP_SHIFT_RIGHT      29
#define T__109      109
#define IDENTIFIER      64
#define T__103      103
#define BREAK_STAT      57
#define T__104      104
#define T__105      105
#define T__106      106
#define T__111      111
#define T__110      110
#define ARGUMENT_LIST      47
#define T__113      113
#define T__112      112
#define OP_DIV_ASSIGN      9
#define FLOAT_EXPONENT      71
#define DICT_ELEM_VALUE      63
#define OP_SHIFT_LEFT      28
#define T__102      102
#define T__101      101
#define T__100      100
#define INCLUDE_FILENAME      75
#define OP_POST_DECR      36
#define RETURN_STAT      60
#define CONTINUE_STAT      58
#define DO_WHILE_STAT      54
#define FLOAT_LITERAL      70
#define EMPTY_EXPR      56
#define OP_AND_ASSIGN      13
#define OP_ADD_ASSIGN      6
#define OP_NEGATE      39
#define OP_SHIFT_LEFT_ASSIGN      11
#define DICT_VALUE      62
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for gruntParser
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
